### ISSUE TITLE
Need fix and redesign some icons

### ISSUE THREAD

**Issue by varlesh** [PapirusDevelopmentTeam/papirus-calibre-theme#4]
**Pixel align:**
_Comment: Please enable grid (Shift+3 and SEE!!!). Also maybe lines need draw as like style `git` icon (on main theme)_
- merge.svg
- merge_books.svg
- plusplus.svg

**Green on green:**
_Comment: It's unreadable, colors merged. Need change color_
- similar.svg
- store.svg

**Merged colors:**
_Comment: Lines and hand merged, it's not good._
- toc.svg

**Toxic green:**
_Comment: We not use toxic and very bright colors._
- plugins/plugin_disabled_valid.svg
- plugins/plugin_new_valid.svg
- plugins/plugin_upgrade_valid.svg

**Comment by SmartFinn** [comment]
> Green on green
> Comment: It's unreadable, colors merged. Need change color
>
> similar.svg
> store.svg

This's my fault. @morealaz used one color for all context circles, but it's not the best idea.

**Comment by SmartFinn** [comment]
@varlesh what about [add_book.svg](https://github.com/PapirusDevelopmentTeam/papirus-calibre-theme/blob/master/imgsrc/add_book.svg)? Can we use the green color or another color shade of green?

**Comment by varlesh** [comment]
@SmartFinn я убегаю... позже решим или на твой вкус ))

**Comment by ghost** [comment]
@varlesh : sorry, I'm not a professional and excellent designer like you and @SmartFinn, I just want to help you guys in this wonderful project of your's (Papirus). It's all I can do. can you please fix them by yourself?
